version: "3.8"

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/instagram
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=CvtmQ3qHLamteT2yh
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=CvtmQ3qHLamteT2yh
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
